### ISSUE TITLE
Wonkiness with width/height properties

### ISSUE THREAD

**Issue by davecrow** [jordandobson/framer-DevicePixelRatio#2]
I'm trying to implement the module here:
https://github.com/davecrow/sightWords/tree/devicePixelRatio

When I apply the `dpr` function to the width of a layer, it forces the height to be 200. In the project above, the bottom button uses `dpr` and the top doesn't. But they should be the same size.

Here's a simple example (remove `dpr` from width and it behaves correctly):
http://share.framerjs.com/mfbg60iys8k6/

I thought maybe some of the recent updates to Framer broke the module. If you have a chance to check it out that'd be great. Thanks Jordan!

**Comment by jordandobson** [comment]
It looks like it's just a matter of how you are formatting the layer...

This worked for me:
![ScreenShot](http://jrdn.io/1r2m0u0m2I0u/Screen%20Shot%202016-11-14%20at%203.28.33%20PM.png)

Instead of this: 
![ScreenShot](http://jrdn.io/0i3u1H132K3C/Screen%20Shot%202016-11-14%20at%203.32.44%20PM.png)

Whats happening in your version is that the dpr() function is picking up everything after 300, as an argument to that function... so it's looking at it like this...

`width: dpr(300, height: dpr(300))`

instead of what you want which should be this...

`width: dpr(300), height: dpr(300)`

So either wrap the parenthesis around the entire dpr statement `(dpr 300)` (that's what I typically do) or define it as a traditional function like `dpr(300)`. Either one should work.

**Comment by davecrow** [comment]
Makes total sense. Why didn't I think of that?!

Thanks for the feedback!
